/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_chm4j_ChmEntry */

#ifndef _Included_org_chm4j_ChmEntry
#define _Included_org_chm4j_ChmEntry
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_chm4j_ChmEntry
 * Method:    readContent
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_chm4j_ChmEntry_readContent
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
