/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_greenlemonmobile_app_ebook_ndk_NDKInitialize */

#ifndef _Included_com_greenlemonmobile_app_ebook_ndk_NDKInitialize
#define _Included_com_greenlemonmobile_app_ebook_ndk_NDKInitialize
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_greenlemonmobile_app_ebook_ndk_NDKInitialize
 * Method:    environmentDetect
 * Signature: (Landroid/app/Activity;[BIZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_greenlemonmobile_app_ebook_ndk_NDKInitialize_environmentDetect(JNIEnv *, jclass, jobject, jbyteArray, jint, jboolean);

//__attribute__ ((visibility("default")))void test(JNIEnv * env, jobject);

/*
 * Class:     com_greenlemonmobile_app_ebook_ndk_NDKInitialize
 * Method:    constructEnvironment
 * Signature: (Landroid/app/Activity;[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_greenlemonmobile_app_ebook_ndk_NDKInitialize_constructEnvironment(JNIEnv *, jclass, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
